version: "3.5"

services:
  bank-accounts:
    container_name: bank-accounts
    build: .
    restart: always
    ports:
      - 8082:8082
    networks: 
      - bank-network

networks: 
  bank-network:
    external: 
      name: bank-network